services:
  # NGINX - reverse proxy with ssl
  nginx:
    image: nginx:alpine
    container_name: nextcloud-nginx
    hostname:       nextcloud-nginx
    volumes:
      - type: bind
        source: ./config/nginx/nextcloud.conf
        target:  /etc/nginx/conf.d/default.conf
        read_only: true

      - type: volume
        source: nextcloud-app-volume
        target: /var/www/html
        read_only: true
      
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      - type: bind
        source: ./ssl
        target:  /etc/nginx/ssl
        read_only: true

    networks:   ['nextcloud']
    ports:      ['80:80', '443:443']
    depends_on: ['nextcloud']
    restart: unless-stopped

  # NEXTCLOUD - app
  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud-app
    hostname:       nextcloud-app
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: localhost payva-u.yooteam.ru 192.168.0.106
      NEXTCLOUD_ADMIN_USER:      admin
      NEXTCLOUD_ADMIN_PASSWORD: $NEXTCLOUD_ADMIN_PASSWORD
      POSTGRES_HOST:             nextcloud-postgres
      POSTGRES_DB:              $POSTGRES_DB
      POSTGRES_USER:            $POSTGRES_USER
      POSTGRES_PASSWORD:        $POSTGRES_PASSWORD
      REDIS_HOST:                nextcloud-redis
    volumes:
      - type: volume
        source: nextcloud-app-volume
        target: /var/www/html
        read_only: false

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

    networks:   ['nextcloud']
    depends_on: ['postgres', 'redis']
    restart: unless-stopped

  # POSTGRES - db
  postgres:
    image: postgres:alpine
    container_name: nextcloud-postgres
    hostname:       nextcloud-postgres
    environment:
      POSTGRES_DB:       $POSTGRES_DB
      POSTGRES_USER:     $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - type: volume
        source: nextcloud-postgres-volume
        target: /var/lib/postgresql/data
        read_only: false

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      #- type: bind
      #  source: ./ssl
      #  target:  /var/lib/postgresql/ssl
      #  read_only: true

      #- type: bind
      #  source: ./config/postgres
      #  target:  /docker-entrypoint-initdb.d/
      #  read_only: true
        
    networks: ['nextcloud']
    restart: unless-stopped

  # REDIS - cache
  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname:       nextcloud-redis
    networks: ['nextcloud']
    restart: unless-stopped


volumes:
  nextcloud-app-volume:
    name: nextcloud-app-volume
  nextcloud-postgres-volume:
    name: nextcloud-postgres-volume
